"""empty message

Revision ID: 26f17211d9aa
Revises: 4d0c20763490
Create Date: 2022-01-06 16:55:20.579229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f17211d9aa'
down_revision = '4d0c20763490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('url', sa.String(length=255), nullable=True))
    op.add_column('User', sa.Column('data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'data')
    op.drop_column('User', 'url')
    # ### end Alembic commands ###
