"""empty message

Revision ID: 42a56682fdee
Revises: cee6a2db6776
Create Date: 2022-01-07 14:03:40.599244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a56682fdee'
down_revision = 'cee6a2db6776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('passwordHash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'passwordHash')
    # ### end Alembic commands ###
