"""empty message

Revision ID: 4d0c20763490
Revises: f1f518714fb0
Create Date: 2022-01-04 20:37:47.603947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0c20763490'
down_revision = 'f1f518714fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('User', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'time_updated')
    op.drop_column('User', 'time_created')
    # ### end Alembic commands ###
