"""empty message

Revision ID: 5baa9a7c1c45
Revises: 8ca5203f9fff
Create Date: 2022-02-05 19:31:21.243075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5baa9a7c1c45'
down_revision = '8ca5203f9fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recipe', sa.Column('recipe_list_name', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Recipe', 'RecipeList', ['recipe_list_name'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Recipe', type_='foreignkey')
    op.drop_column('Recipe', 'recipe_list_name')
    # ### end Alembic commands ###
