"""empty message

Revision ID: 789338cdeaa2
Revises: 5baa9a7c1c45
Create Date: 2022-02-05 19:41:50.210299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789338cdeaa2'
down_revision = '5baa9a7c1c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recipe', sa.Column('recipe_list_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Recipe', 'recipe_list_name')
    # ### end Alembic commands ###
