"""empty message

Revision ID: 8ca5203f9fff
Revises: a438e6fe3b5d
Create Date: 2022-01-29 10:35:49.342638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca5203f9fff'
down_revision = 'a438e6fe3b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RecipeList',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Recipe', sa.Column('recipe_list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Recipe', 'RecipeList', ['recipe_list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Recipe', type_='foreignkey')
    op.drop_column('Recipe', 'recipe_list_id')
    op.drop_table('RecipeList')
    # ### end Alembic commands ###
