"""empty message

Revision ID: 9e9ed5c21602
Revises: acc8e1673ecc
Create Date: 2022-10-07 15:35:49.584378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9ed5c21602'
down_revision = 'acc8e1673ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recipe', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Recipe', 'views')
    # ### end Alembic commands ###
