"""empty message

Revision ID: cee6a2db6776
Revises: 26f17211d9aa
Create Date: 2022-01-07 11:54:54.080514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee6a2db6776'
down_revision = '26f17211d9aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'username')
    # ### end Alembic commands ###
